name: Building CI on Unity for Team 1 PFE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_NAME: PFE_TestCI  # Définir le nom du projet comme variable d'environnement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Start Time
        run: echo "START_TIME=$(TZ=":Europe/Paris" date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV

      - name: Checking out Git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get last successful build date
        id: last-build
        run: |
          echo "LAST_BUILD_DATE=$(git log --pretty=format:'%cd' -1 --date=iso)" >> $GITHUB_ENV

      - name: Get commits since last build
        id: commits
        run: |
          COMMITS=$(git log --pretty=format:'[%h](https://github.com/${{ github.repository }}/commit/%h) - %s - %an' --since="${{ env.LAST_BUILD_DATE }}")
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set Build Name
        run: echo "BUILD_NAME=PFE1_StandaloneWindows64_${{ env.START_TIME }}" >> $GITHUB_ENV

      - name: Build execution time - start
        id: build-execution-time-start
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Registering License
        id: project-build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildName: ${{ env.BUILD_NAME }}
          buildsPath: Builds
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true

      - name: Build execution time - end
        id: build-execution-time
        run: |
          end_time=$(date +%s)
          duration=$((end_time - ${{ env.start_time }}))
          echo "duration=$duration" >> $GITHUB_OUTPUT

      - name: Storing Build Artefact
        id: build-upload
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ env.BUILD_NAME }}
          path: Builds/StandaloneWindows64
          retention-days: 14

      - name: List files in Builds directory (Debug)
        run: ls -R ${{ github.workspace }}/Builds

      - name: Upload Unity Build Logs
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ env.BUILD_NAME }}_Logs
          path: ${{ github.workspace }}/Builds/StandaloneWindows64/*.log
          if-no-files-found: warn

      - name: Get build artifact URL
        id: build-artifact-url
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" \
            | jq -r '.artifacts[] | select(.name == "${{ env.BUILD_NAME }}") | .id')
          echo "BUILD_ARTIFACT_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/$ARTIFACT_ID" >> $GITHUB_ENV

      - name: Get logs artifact URL
        id: logs-artifact-url
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" \
            | jq -r '.artifacts[] | select(.name == "${{ env.BUILD_NAME }}_Logs") | .id')
          echo "LOGS_ARTIFACT_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/$ARTIFACT_ID" >> $GITHUB_ENV

      - name: Set build status
        id: build-status
        run: |
          if [ "${{ steps.project-build.outputs.engineExitCode }}" -eq "0" ]; then
            echo "STATUS=Réussie ✅" >> $GITHUB_ENV
            echo "COLOR=65280" >> $GITHUB_ENV
          else
            echo "STATUS=Échouée ❌" >> $GITHUB_ENV
            echo "COLOR=16711680" >> $GITHUB_ENV
          fi

      - name: Send Discord notification
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: "Unity Build Bot"
          avatar-url: "https://unity.com/favicon.ico"
          embed-title: "Build Unity ${{ env.STATUS }} - ${{ env.START_TIME }}"
          embed-description: |
            **Détails de la build:**
            - **Nom:** ${{ env.BUILD_NAME }}
            - **Plateforme:** StandaloneWindows64
            - **Durée d'exécution:** ${{ steps.build-execution-time.outputs.duration }} secondes
            - **Code de sortie:** ${{ steps.project-build.outputs.engineExitCode }}

            **Commits depuis la dernière build:**
            ${{ env.COMMITS }}

            **Liens Utiles:**
            - [Télécharger la build](${{ env.BUILD_ARTIFACT_URL }})
            - [Détails du workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          embed-color: ${{ env.COLOR }}
          embed-footer-text: "Team 1 PFE - Build générée le ${{ env.START_TIME }}"

      - name: Caching
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/${{ env.PROJECT_NAME }}/Library  # Utilisation de la variable d'environnement
          key: Library-${{ env.PROJECT_NAME }}-TargetPlatform  # Utilisation de la variable d'environnement
          restore-keys: |
            Library-${{ env.PROJECT_NAME }}-
            Library-
        if: exists('${{ github.workspace }}/${{ env.PROJECT_NAME }}/Library')

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.